In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a,type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
#0-D numpy array
print('#----------------------')
a=np.array(1)
print(a,type(a),a.ndim,a.shape)
print('#----------------------')
#1-D numpy array
a=np.array([1,2])
print(a,type(a),a.ndim,a.shape)
print('#----------------------')
#2-D numpy array
a=np.array([[1,2]])
print(a,type(a),a.ndim,a.shape)
print('#----------------------')
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a,type(a),a.ndim,a.shape)
print('#----------------------')
a = np.array([[[1, 2], [4, 5],[7,8]], [[1, 2], [4, 5],[7,8]]])
print(a,type(a),a.ndim,a.shape)
print('#----------------------')

#----------------------
1 <class 'numpy.ndarray'> 0 ()
#----------------------
[1 2] <class 'numpy.ndarray'> 1 (2,)
#----------------------
[[1 2]] <class 'numpy.ndarray'> 2 (1, 2)
#----------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'> 3 (2, 2, 3)
#----------------------
[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]] <class 'numpy.ndarray'> 3 (2, 3, 2)
#----------------------


In [6]:
import numpy as np
# 2nd element on 1st row:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

#5th element on 2nd row

print(arr[1,4])

2
10


# The Difference Between Copy and View
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

# The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

# The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [7]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
a=np.arange(9)
a=a.reshape(3,3)
print(a,a.shape,a.ndim)
print("COL WISE SUM",np.sum(a,axis=1))
print("ROW WISE SUM",np.sum(a,axis=0))
print("--------------------")
a=np.arange(8)
a=a.reshape(4,2,-1)
print(a)
print("--------------------")
print(a.flatten())
print("--------------------")
a=a.reshape(-1)
print(a.reshape(-1))

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3) 2
COL WISE SUM [ 3 12 21]
ROW WISE SUM [ 9 12 15]
--------------------
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]]
--------------------
[0 1 2 3 4 5 6 7]
--------------------
[0 1 2 3 4 5 6 7]


In [10]:
#------------slicing
print(a[0:4])
print(a[0:4:2])
a=np.arange(8)
a=a.reshape(4,2)
print(a,a.shape,a.ndim)

[0 1 2 3]
[0 2]
[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2) 2


In [11]:
#CONCATENATE
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr,arr.shape)

[1 2 3 4 5 6] (6,)


In [12]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr,arr.shape)

arr = np.concatenate((arr1, arr2), axis=1)

print(arr,arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)
[[1 2 5 6]
 [3 4 7 8]] (2, 4)


# SPLIT , Merge & BroadCasting

Splitting arrays - split(), hsplit(), vsplit()
Merging Arrays - hstack(), vstack(), concatenate()
 **Broadcasting**
    - `np.tile()` 


In [13]:
#--------- split

a=np.arange(8)
print(a)
a = np.split(a, 2)
print(a)
a=np.arange(8)
a = np.split(a, 4)
print(a)
#from index 2 upto the index 6 but not 6
a=np.arange(8)
a = np.hsplit(a, [2,6])
print(a)
#-----------------------------------------
#a=np.arange(8)
#a = np.vsplit(a,2)
#print(a)
#This will throw error bcoz vsplit does not work for 1D array
#------------------------------------------
a=np.arange(8).reshape(4,2)
print("BEFORE VSPLIT",a)
a = np.vsplit(a,2)
print("AFTER VSPLIT",a)

[0 1 2 3 4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
[array([0, 1]), array([2, 3, 4, 5]), array([6, 7])]
BEFORE VSPLIT [[0 1]
 [2 3]
 [4 5]
 [6 7]]
AFTER VSPLIT [array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]])]


In [14]:
a=np.arange(8).reshape(4,2)
print(a)
print("------------------ARRAYS-----------------------------")
b=np.arange(8,16).reshape(4,2)
print(b)
print("-------------------HSTACK----------------------------")
c = np.hstack((a, b))
print(c)
print("-------------------VSTACK----------------------------")
d = np.vstack((a, b))
print(d)
print("-----------------CONCATENATION--on AXIS=0----------------------------")
e = np.concatenate((a,b),axis=0)
print(e)
print("-----------------CONCATENATION--on AXIS=1----------------------------")
f = np.concatenate((a,b),axis=1)
print(f)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
------------------ARRAYS-----------------------------
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
-------------------HSTACK----------------------------
[[ 0  1  8  9]
 [ 2  3 10 11]
 [ 4  5 12 13]
 [ 6  7 14 15]]
-------------------VSTACK----------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
-----------------CONCATENATION--on AXIS=0----------------------------
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
-----------------CONCATENATION--on AXIS=1----------------------------
[[ 0  1  8  9]
 [ 2  3 10 11]
 [ 4  5 12 13]
 [ 6  7 14 15]]


#SEARCH IN NUMPY

#You can search an array for a certain value, and return the indexes that get a match.


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [16]:
a=np.arange(12)
print(a<3)
print(a[a<3])
print(a[a%3==0])

[ True  True  True False False False False False False False False False]
[0 1 2]
[0 3 6 9]


In [17]:
import numpy as np
a=np.array([1,2,4])
mask = (a%2==0)


In [18]:
mask

array([False,  True,  True])

In [19]:
a[mask]

array([2, 4])

In [20]:
a[mask]=-1
a[mask]

array([-1, -1])

In [21]:

# importing the module
import numpy as np
 
# create an array
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')
 
# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')
 
# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

Array to be appended column wise
[[ 5  6  7  8  9 10]]
Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 

Array to be appended row wise
[[1]
 [2]]
Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


#SLICING AND INDEXING

In [44]:
a=np.arange(1,10).reshape(3,3)
print(a)
print("-------------")
#GET 1st row
print(a[0])
print("-------------")
#GET 3 row
print(a[2])
print("-------------")
#GET 1st COLUMN
print(a[:,0])
print("-------------")
#GET 3 COLUMN
print(a[:,2])
print("-------------")
#GET 1st row and 3 COLUMN
print(a[0,2])
print("-------------")
#GET 3rd row and 3 COLUMN
print(a[2,2])
print("-------------")
#GET 3rd row and 3 COLUMN
print(a[:,0::2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
[1 2 3]
-------------
[7 8 9]
-------------
[1 4 7]
-------------
[3 6 9]
-------------
3
-------------
9
-------------
[[1 3]
 [4 6]
 [7 9]]


In [45]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a, b

(array([1, 2, 3, 4]), array([4, 3, 2, 1]))

In [46]:
np.all(a<b)

False

In [47]:
np.any(a<b)

True

In [49]:
np.sort(b)

array([1, 2, 3, 4])