**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [8]:
a,b=input().split()
a=int(a)
b=int(b)
c=np.random.randint(low=0,high=100,size=(a,b))
print(c)
print(np.average(c))
print(np.mean(c))
#summation of all elements / number of elements

[[37 50 42 39]
 [31 22  0 47]
 [72 72 26 30]]
39.0
39.0


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [18]:
#Code here
a,b=input().split()
a=int(a)
b=int(b)
c=np.zeros((a,b))
#first row
c[0,:]=1
#last row
c[-1,:]=1
#first column
c[:,0]=1
#last column
c[:,-1]=1
print(c)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [28]:
#Code here
a=np.linspace(0,1,12)
a=a[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [37]:
#Code here
#identity matrix means having same rows and columns we have alternate methods 
a=np.identity(3)
print('matrix 1\n',a)
#method 2
import numpy as np

# Create a matrix with 1s on the diagonal and 0s elsewhere
matrix = np.zeros((3, 4))

# Set the diagonal elements to 1
np.fill_diagonal(matrix, 1)

print('matrix-2\n',matrix)



matrix 1
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
matrix-2
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [38]:
a=np.random.randint(low=0,high=4,size=(5,5))
print(a)

[[3 2 3 0 0]
 [0 3 1 2 1]
 [0 1 3 2 0]
 [2 0 3 3 3]
 [2 0 3 3 2]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [43]:
a=np.random.randint(low=1,high=100,size=((10,2)))
print(a)
print("\n")
b = np.array([2,3])
print("\n")
print(a-b)

[[65 13]
 [71 78]
 [71 68]
 [59 76]
 [78 29]
 [38 22]
 [73  4]
 [ 7 77]
 [23 13]
 [42 94]]




[[63 10]
 [69 75]
 [69 65]
 [57 73]
 [76 26]
 [36 19]
 [71  1]
 [ 5 74]
 [21 10]
 [40 91]]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [78]:
#Code here
a=np.arange(336)
a=a.reshape(6,7,8)
print(a[1][5][3])
#or
b=np.ravel(a)
print(b[99])

99
99


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [107]:
a=np.array([1,2,3,4,-8,-10],dtype=int)
print(a)
b=a[::-1]
b=b.astype(float)
print(b)

[  1   2   3   4  -8 -10]
[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [109]:
#Code here
a=np.arange(1,10)
b=np.array([])
print("elements count",len(a))
print("elements count",len(b))

elements count 9
elements count 0


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [154]:
#Code here
a=np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318])
b=np.exp(a)
c=np.sum(b)
d=b/c
print(d)

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= 
[[1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [164]:
#Coder here
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
b=np.array([[1,1,1,1,1],[1,1,1,1,1]])
c=np.array([[0.10117373,0.1677244 ,0.73764059,0.83166097,0.48985695],
            [0.44581567,0.13502419,0.55692335,0.16479622,0.61193593]])
d=np.vstack((a,b))
d=np.vstack((d,c))
print(d)

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [165]:
#Code here
def date_array(date1,date2):
    date1=np.datetime64(date1)
    date2=np.datetime64(date2)
    a=np.arange(date1,date2)
    return a

print(date_array('2020-01-01','2020-01-10'))

['2020-01-01' '2020-01-02' '2020-01-03' '2020-01-04' '2020-01-05'
 '2020-01-06' '2020-01-07' '2020-01-08' '2020-01-09']


###`Q-14:` Subtract the mean of each row from a matrix.

In [166]:
#code here
a=np.arange(9).reshape(3,3)
print(a-np.mean(a))

[[-4. -3. -2.]
 [-1.  0.  1.]
 [ 2.  3.  4.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [172]:
#Code here
a=np.arange(9).reshape(3,3)
print(a)
a[:,0],a[:,1]=a[:,1].copy(),a[:,0].copy()
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


###`Q-16:` Replace odd elements in arrays with -1.

In [176]:
#Code here
a=np.arange(9).reshape(3,3)
print(a)
a%2!=0
a[~(a%2==0)]=-1
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [182]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=[]
for i in range(len(a)):
    if a[i]>b[i]:
        c.append(a[i])
    else:
        c.append(b[i])
print(c)
    
    
#Method 2
import numpy as np

a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

# Use np.maximum to get element-wise maximum
result = np.maximum(a, b)

print(result)



[6, 3, 1, 7, 8]
[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [184]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr2=arr1-np.min(arr1)/np.max(arr1)-np.min(arr1)
print(arr2)

[[ 5.31597788e+03  4.05697788e+03  4.74497788e+03  2.14997788e+03
   6.63397788e+03]
 [ 5.53797788e+03  4.93397788e+03  8.67497788e+03  5.62297788e+03
   7.02297788e+03]
 [ 3.34897788e+03  4.96497788e+03  3.58997788e+03  5.39597788e+03
   5.94977878e+02]
 [-2.21216692e-02  2.57797788e+03  2.64897788e+03  7.08197788e+03
   1.97797788e+03]
 [ 4.06297788e+03  8.81297788e+03  8.80797788e+03  5.13097788e+03
   2.99697788e+03]
 [ 4.22397788e+03  8.90197788e+03  9.72497788e+03  2.84197788e+03
   7.51197788e+03]
 [ 8.29597788e+03  8.77977878e+02  2.41197788e+03  7.63977878e+02
   4.67297788e+03]
 [ 4.82397788e+03  5.91497788e+03  2.50977878e+02  7.06297788e+03
   7.62097788e+03]]


: 

In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [149]:
#Code here

def largest_index(arr,n):
    if arr.size==0 or n>arr.size:
        return -1
    else:
        return np.sort(arr)[-n]
arr = np.array([12,34,40,7,1,0])
n=3
print(largest_index(arr,n))


12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [128]:
#code here
a=np.arange(1,4)
b=np.full((3,3),a)
c=b.T
list_1=np.ravel(c)
list_2=np.ravel(b)
final=np.concatenate((list_1,list_2))
print(final)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
