###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [2]:
# code here
import numpy as np

# Create a random 3x4 matrix with values between 0 and 100
matrix = np.random.randint(0, 101, size=(3, 4))

print("Original Matrix:")
print(matrix)

# i. Sort the entire matrix
sorted_matrix = np.sort(matrix, axis=None).reshape(matrix.shape)
print("\nSorted Matrix (all elements sorted):")
print(sorted_matrix)

# i. Sort the Row matrix
sorted_row_matrix = np.sort(matrix, axis=1)
print("\Row Sorting Matrix")
print(sorted_row_matrix)

# i. Sort the Column matrix
sorted_col_matrix = np.sort(matrix, axis=0)
print("\Column Sorting Matrix")
print(sorted_col_matrix)




# ii. Sort the matrix based on values in the 2nd column (index 1)

sorted_by_column_2 = matrix[matrix[:, 1].argsort()]
print(sorted_by_column_2)

# iii. Sort the matrix based on the max value in each row
sorted_by_max_in_row = matrix[matrix.max(axis=1).argsort()]
print("\nSorted Matrix by Max Value in Each Row:")
print(sorted_by_max_in_row)

# iv. Sort based on the values of the elements (flatten, sort, and reshape)
sorted_by_elements = np.sort(matrix, axis=None).reshape(matrix.shape)
print("\nSorted Matrix based on Elements Value:")
print(sorted_by_elements)



Original Matrix:
[[43 95 40 75]
 [72 97  4 75]
 [45 36 44 91]]

Sorted Matrix (all elements sorted):
[[ 4 36 40 43]
 [44 45 72 75]
 [75 91 95 97]]
\Row Sorting Matrix
[[40 43 75 95]
 [ 4 72 75 97]
 [36 44 45 91]]
\Column Sorting Matrix
[[43 36  4 75]
 [45 95 40 75]
 [72 97 44 91]]
[[45 36 44 91]
 [43 95 40 75]
 [72 97  4 75]]

Sorted Matrix by Max Value in Each Row:
[[45 36 44 91]
 [43 95 40 75]
 [72 97  4 75]]

Sorted Matrix based on Elements Value:
[[ 4 36 40 43]
 [44 45 72 75]
 [75 91 95 97]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [3]:
# code here

marks = np.random.randint(10,100,size=(5,4))
print(marks)
print(marks.shape)
extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,-1)
print(extra_subject.shape)
print(extra_subject)
arr = np.concatenate((marks,extra_subject),axis=1)
print("---------------------------------------------------------")
extra_student1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
extra_student2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
arr = np.concatenate((arr,extra_student1),axis=0)
arr = np.concatenate((arr,extra_student2),axis=0)
print("---------------------------------------------------------")
sum = np.sum(arr,axis=1).reshape(-1,1)
arr = np.concatenate((arr,sum),axis=1)
print(sum)
print("---------------------------------------------------------")

print(arr[arr[:,-1].argsort()[::-1]])

print("top 2 rows")
print(arr[arr[:,-1].argsort()[::-1]][:2])




[[75 25 72 55]
 [88 52 83 12]
 [46 96 29 96]
 [24 43 25 79]
 [16 62 31 40]]
(5, 4)
(5, 1)
[[41]
 [87]
 [72]
 [36]
 [92]]
---------------------------------------------------------
---------------------------------------------------------
[[268]
 [322]
 [339]
 [207]
 [241]
 [442]
 [329]]
---------------------------------------------------------
[[ 77  83  98  95  89 442]
 [ 46  96  29  96  72 339]
 [ 92  71  52  61  53 329]
 [ 88  52  83  12  87 322]
 [ 75  25  72  55  41 268]
 [ 16  62  31  40  92 241]
 [ 24  43  25  79  36 207]]
top 2 rows
[[ 77  83  98  95  89 442]
 [ 46  96  29  96  72 339]]



- Feature	np.concatenate()|np.append()
- Input type	Takes a sequence of arrays (list or tuple).	| Takes an array and the values to append.
- Flexibility	More flexible: can concatenate along any axis.	| Less flexible: appends along the specified axis (or flattens arrays).
- Flattening	Does not flatten arrays unless specified.	| Flattens arrays by default unless axis is specified.
- Use case	Suitable for combining arrays in multiple dimensions.| Convenient for adding elements to the end of an array.
- Performance	Generally faster for combining large arrays. | Slightly slower due to flattening behavior.


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [4]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

print(np.unique(arr,axis=0))

print(np.unique(arr,axis=1))


[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [5]:
# code here
a=np.arange(9).reshape(3,3)
print(a)
print(np.flip(a,axis=0))
print(np.flip(a,axis=1))
flipped = np.flip(a, axis=(0, 1))
print(flipped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[8 7 6]
 [5 4 3]
 [2 1 0]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [6]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])

arr[np.max(arr,axis=1)>6]

array([[10, -3, 30,  4,  5],
       [ 9,  7,  3,  6,  5]])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [7]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
combined = np.concatenate([arr1, arr2, arr3])
print(combined)


[0 1 2 3 4 5 6 7 8 9]


In [8]:
# code here

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [9]:
# code here
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
print(np.argmax(arr))
print(arr[:,np.argmax(arr)])
np.delete(arr,[np.argmax(arr)])
print(arr[:,np.argmin(arr)])
print(np.argmin(arr))
np.delete(arr,[np.argmin(arr)])


[[799 332 851 301 721 588 924 511 663 724 309 405 783 801 223 690 242 585
  134 376 393 832 472 134 324 443 776 275 369 797 940 556 453 424 413 162
  139 773 197 143 635 593 118 289 586 513 521 992 429 251 193 920 230 131
  924 221 201 776 797 325 110 860 492 826 374 852 867 565 236 898 413 461
  415 785 628 350 796 955 187 581 424 269 490 996 383 773 999 912 635 419
  181 930 268 810 757 736 541 656 143 872 200 369 599 290 658 605 513 788
  575 752 811 673 117 435 815 360 999 532 478 339 656 494 644 175 676 696
  296 909 146 530 692 957 564 755 122 752 482 385 951 884 607 780 473 859
  363 245 181 688 962 815 558 733 689 333 571 736 240 109 555 915 290 267
  233 284 378 691 760 474 919 845 346 937 942 838 453 292 125 676 235 647
  368 977 974 582 333 639 621 454 331 102 328 808 466 158 733 329 772 349
  156 361]]
86
[999]
[102]
189


array([799, 332, 851, 301, 721, 588, 924, 511, 663, 724, 309, 405, 783,
       801, 223, 690, 242, 585, 134, 376, 393, 832, 472, 134, 324, 443,
       776, 275, 369, 797, 940, 556, 453, 424, 413, 162, 139, 773, 197,
       143, 635, 593, 118, 289, 586, 513, 521, 992, 429, 251, 193, 920,
       230, 131, 924, 221, 201, 776, 797, 325, 110, 860, 492, 826, 374,
       852, 867, 565, 236, 898, 413, 461, 415, 785, 628, 350, 796, 955,
       187, 581, 424, 269, 490, 996, 383, 773, 999, 912, 635, 419, 181,
       930, 268, 810, 757, 736, 541, 656, 143, 872, 200, 369, 599, 290,
       658, 605, 513, 788, 575, 752, 811, 673, 117, 435, 815, 360, 999,
       532, 478, 339, 656, 494, 644, 175, 676, 696, 296, 909, 146, 530,
       692, 957, 564, 755, 122, 752, 482, 385, 951, 884, 607, 780, 473,
       859, 363, 245, 181, 688, 962, 815, 558, 733, 689, 333, 571, 736,
       240, 109, 555, 915, 290, 267, 233, 284, 378, 691, 760, 474, 919,
       845, 346, 937, 942, 838, 453, 292, 125, 676, 235, 647, 36

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [16]:
# code here
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

#in clip any value <100 will be replaced by 100 and >200 will be replaced by 200
arr = np.clip(arr,100,200)

# Step 2: Sort the array
arr_sorted = np.sort(arr)

# Step 3: Perform cumulative sum
cumulative_sum = np.cumsum(arr_sorted)

# Print the result
print(cumulative_sum)

[  100   209   327   446   567   691   815   946  1083  1220  1357  1500
  1651  1802  1967  2133  2301  2470  2645  2832  3023  3220  3420  3620
  3820  4020  4220  4420  4620  4820  5020  5220  5420  5620  5820  6020
  6220  6420  6620  6820  7020  7220  7420  7620  7820  8020  8220  8420
  8620  8820  9020  9220  9420  9620  9820 10020 10220 10420 10620 10820
 11020 11220 11420 11620 11820 12020 12220 12420 12620 12820 13020 13220
 13420 13620 13820 14020 14220 14420 14620 14820 15020 15220 15420 15620
 15820 16020 16220 16420 16620 16820 17020 17220 17420 17620 17820 18020
 18220 18420 18620 18820 19020 19220 19420 19620 19820 20020 20220 20420
 20620 20820 21020 21220 21420 21620 21820 22020 22220 22420 22620 22820
 23020 23220 23420 23620 23820 24020 24220 24420 24620 24820 25020 25220
 25420 25620 25820 26020 26220 26420 26620 26820 27020 27220 27420 27620
 27820 28020 28220 28420 28620 28820 29020 29220 29420 29620 29820 30020
 30220 30420 30620 30820 31020 31220 31420 31620 31

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [27]:
# code here
arr = np.random.random((3,3))
arr = np.round(arr,3)
arr
minimum = np.percentile(arr,0)
print(minimum)
maximum = np.percentile(arr,100)
print(maximum)
a50_percentile = np.percentile(arr,50)
print(a50_percentile)
a51_percentile = np.percentile(arr,51)
print(a51_percentile)
print("diffence",a51_percentile-a50_percentile)


0.094
0.82
0.489
0.48956
diffence 0.0005600000000000049
