Questions on NumPy Array

In [6]:
#How to create an empty and a full NumPy array?
import numpy as np
  
#numpy.empty :- Return a new array of given shape and type, with random values.
#numpy.full :-  Return a new array with the same shape and type as a given array filled with a fill_value.

# Create an empty array
arr = np.empty((3, 4), dtype=int)
print("Empty Array")
print(arr)
  
# Create a full array
arr1 = np.full([3, 3], 100, dtype=int)
print("\n Full Array")
print(arr1)



Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array
[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [11]:
#Create a Numpy array filled with all zeros
arr = np.zeros([3,4], dtype = int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
#Create a Numpy array filled with all ones
arr = np.ones([3,4], dtype = int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
#Check whether a Numpy array contains a specified row



arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])

print(arr.tolist())

print([1, 2, 3, 4, 5] in arr.tolist())
#------------------------------------------------------or
arr = np.random.rand(9).reshape(3,3)
print(arr)
#----or
arr = np.random.randint(9, size=9).reshape(3,3)
print(arr)


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
True
[[0.0527003  0.09913698 0.26823802]
 [0.03105203 0.49064427 0.17374576]
 [0.88580755 0.80327115 0.53319973]]
[[5 4 0]
 [2 4 6]
 [7 5 0]]


In [74]:
#Method 2
print(arr)
np.where((arr == [5,4,0]).all(axis=1))

[[5 4 0]
 [2 4 6]
 [7 5 0]]


(array([0], dtype=int64),)

In [135]:
#How to Remove rows in Numpy array that contains non-numeric values?
nparray=np.array([[1,2,3,4],['s','q',1,4],[1.2,4.2,32,4]])
print(nparray.shape)

for i in range(nparray.shape[0]):
    for j in range(nparray.shape[1]):
        try:
            if int(nparray[i][j]):
                pass
        except Exception as e:
            nparray[i][j]= False
            
arr2 = nparray[nparray !='False'].astype(int)
print(arr2)

(3, 4)
[ 1  2  3  4  1  4 32  4]


In [202]:
import numpy as np
  
# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:",)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


In [203]:
#Make into single dimentional array
x = np.array([[[0], [1], [2]]])
print(x.flatten())

[0 1 2]


In [204]:
#Find the number of occurrences of a sequence in a NumPy array
# importing package
import numpy

# create numpy array
arr = numpy.array([[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7],[2, 9, 4, 3]])

# Counting sequence
output = repr(arr).count("4")

# view output
print(output)


arr = numpy.array([[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7],[2, 9, 4, 3]])
print(arr.flatten().tolist().count(4))
print(len(arr[np.where(arr==4)]))


5
5
5


In [222]:
#Find the most frequent value in a NumPy array
x = np.array([1,1,1,2,2,2,5,25,1,1,4,4,4,4,4,4,4,4,4,4,4])
unique, numbers = np.unique(x, return_counts=True)
print(unique)
print(numbers)

[ 1  2  4  5 25]
[ 5  3 11  1  1]


In [223]:
unique[np.argmax(numbers)]

4

In [230]:
#Combining a one and a two-dimensional NumPy Array
import numpy as np
  
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
  
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


In [9]:
#How to build an array of all combinations of two NumPy arrays?

import numpy as np
  
# creating 2 numpy arrays
array_1 = np.array([1, 2,3])
array_2 = np.array([4, 6,8,10])
  
print("Array-1")
print(array_1)
  
print("\nArray-2")
print(array_2)
  
# combination of elements of array_1 and array_2
# using numpy.meshgrid().T.reshape()
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombine array:")
print(comb_array)

Array-1
[1 2 3]

Array-2
[ 4  6  8 10]

Combine array:
[[ 1  4]
 [ 1  6]
 [ 1  8]
 [ 1 10]
 [ 2  4]
 [ 2  6]
 [ 2  8]
 [ 2 10]
 [ 3  4]
 [ 3  6]
 [ 3  8]
 [ 3 10]]


In [10]:
#How to add a border around a NumPy array?

# importing Numpy package
import numpy as np
  
# Creating a 2X2 Numpy matrix
array = np.ones((2, 2))
  
print("Original array")
print(array)
  
print("\n0 on the border and 1 inside the array")
  
# constructing border of 0 around 2D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)

Original array
[[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [23]:
#How to compare two NumPy arrays?

import numpy as np
 
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
 
comparison = an_array == another_array
equal_arrays = comparison.all()
 
print(comparison)
print(equal_arrays)

[[ True  True]
 [ True  True]]
True


In [31]:
#How to compare two NumPy arrays?

import numpy as np
 
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 5]])
 
comparison = an_array == another_array
equal_arrays = comparison.any()
 
print(comparison)
print(equal_arrays)

[[ True  True]
 [ True False]]
True


In [34]:
print(np.greater_equal(an_array, another_array))
print("-----------------------------------------")
print(np.less(an_array, another_array))
print("-----------------------------------------")

print(np.less_equal(an_array, another_array))

[[ True  True]
 [ True False]]
-----------------------------------------
[[False False]
 [False  True]]
-----------------------------------------
[[ True  True]
 [ True  True]]


In [35]:
#How to check whether specified values are present in NumPy array?

# importing Numpy package
import numpy as np

# creating a Numpy array
n_array = np.array([[2, 3, 0],[4, 1, 6]])

print("Given array:")
print(n_array)

# Checking whether specific values
# are present in "n_array" or not
print(2 in n_array)
print(0 in n_array)
print(6 in n_array)
print(50 in n_array)
print(10 in n_array)



Given array:
[[2 3 0]
 [4 1 6]]
True
True
True
False
False


In [36]:
#How to get all 2D diagonals of a 3D NumPy array?

np.zeros((1, 2, 3, 4))


array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [57]:
import numpy as np
a=[0,1]
n=10
for i in range(10):
    a.append(a[-1]+a[-2])
print(a)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [65]:
def fib(n):
    if n <= 1:
       return 1
    else:
        return fib(n-1)+fib(n-2)
print(fib(3))

3


In [72]:
arr=np.arange(9).reshape(3,3)
len(arr[arr>0])

8

In [74]:
#How to make a NumPy array read-only?
import numpy as np


a = np.zeros(11)
print("Before any change ")
print(a)

a[1] = 2
print("Before after first change ")
print(a)

a.setflags(write=False)
print("After making array immutable on attempting second change ")
a[1] = 7


Before any change 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After making array immutable on attempting second change 


ValueError: assignment destination is read-only

In [93]:
print(arr)
print("----------")
print(np.max(arr))
print("----------")
print(np.min(arr))
print("----------")
print(np.shape(arr))
print("----------")
print(arr[1,1])
print("----------")
print(arr.take(4))
print("----------")
print(np.sum(arr))
print("----------")
print(arr.sum(axis=1))
print("----------")
print(arr.sum(axis=0))
print("----------")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------
8
----------
0
----------
(3, 3)
----------
4
----------
4
----------
36
----------
[ 3 12 21]
----------
[ 9 12 15]
----------


In [95]:
#Calculate the sum of the diagonal elements of a NumPy array


# importing Numpy package
import numpy as np

# creating a 3X3 Numpy matrix
n_array = np.array([[55, 25, 15],
					[30, 44, 2],
					[11, 45, 77]])

# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)

# Finding the diagonal elements of a matrix
diag = np.diagonal(n_array)

print("\nDiagonal elements are:")
print(diag)

print("\nSum of Diagonal elements is:")
print(sum(diag))


Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Diagonal elements are:
[55 44 77]

Sum of Diagonal elements is:
176


In [100]:
#add subtract 2 matrices

import numpy as np
 
 
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 9]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 9]]
Addition of two matrix
[[ 5  7]
 [ 9 13]]
Subtraction of two matrix
[[-3 -3]
 [-3 -5]]
